swagger: "2.0"

info:
  title: "Supplier API"
  version: "1.0"

basePath: /v1.0

paths:
  /suppliers:
    get:
      operationId: api.suppliers.all_suppliers
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Supplier'
  /suppliers/{id}:
    get:
      operationId: api.suppliers.supplier_detail
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Supplier'

definitions:
  Supplier:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }